AppBundle\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [username]
            message: 'This user is already exists.'
    properties:
        username:
        - NotBlank:
            message: 'Username should not be blank.'
        - Length:
            min: 6
            max: 100
            minMessage: 'Username value should be in the range of 6 to 100 characters.'
            maxMessage: 'Username value should be in the range of 6 to 100 characters.'
        password:
        - NotBlank:
            message: 'Password should not be blank.'
        - Length:
            min: 6
            max: 100
            minMessage: 'Password value should be in the range of 6 to 100 characters.'
            maxMessage: 'Password value should be in the range of 6 to 100 characters.'