game_topic:
    channel: app/channel/{user_id}
    handler:
        callback: 'game.topic' #related to the getName() of your topic
    requirements:
        user_id:
            pattern: "\d+"

game_rpc:
    channel: game/{method}
    handler:
        callback: 'game.rpc' #related to the getName() or your RPC service
    requirements:
        method:
            pattern: "[a-z_]+" #accept all valid regex, don't put delimiters !