game_topic:
    channel: app/channel
    handler:
        callback: 'game.topic'

actual_game_topic:
    channel: actual_game/{gameId}
    handler:
        callback: 'actual_game.topic'
    requirements:
        gameId:
            pattern: "\d+"

game_rpc:
    channel: game/{method}
    handler:
        callback: 'game.rpc'
    requirements:
        method:
            pattern: "[a-z_]+"