app:
    resource: "@AppBundle/Controller/"
    type:     annotation

default:
    pattern:     /
    defaults: { _controller: AppBundle:Default:index }

registration:
    pattern:     /register
    defaults: { _controller: AppBundle:User:registerGet }