app:
    resource: "@AppBundle/Controller/"
    type:     annotation

default:
    pattern:     /
    defaults: { _controller: AppBundle:Default:index }

registrationGet:
    pattern:     /users
    defaults: { _controller: AppBundle:User:registerGet }
    methods:  [GET]

registrationPost:
    pattern:     /users
    defaults: { _controller: AppBundle:User:registerPost }
    methods:  [POST]


authorizePost:
    pattern:     /authorize
    defaults: { _controller: AppBundle:Authorization:authorizePost }
    methods:  [POST]


createGameGet:
    pattern:     /createGame
    defaults: { _controller: AppBundle:Game:createGet }
    methods:  [GET]