app:
    resource: "@AppBundle/Controller/"
    type:     annotation

default:
    pattern:     /
    defaults: { _controller: AppBundle:Default:index }

registrationGet:
    pattern:     /users
    defaults: { _controller: AppBundle:User:registerGet }
    methods:  [GET]

registrationPost:
    pattern:     /users
    defaults: { _controller: AppBundle:User:registerPost }
    methods:  [POST]


authorizeGet:
    pattern:     /authorizeGet
    defaults: { _controller: AppBundle:Authorization:authorizeGet }