security:
    encoders:
            AppBundle\Entity\User:
                algorithm: bcrypt

    providers:
        our_db_provider:
            entity:
                class: AppBundle:User
        api_key_user_provider:
            id: api_key_user_provider

    providers:
        in_memory:
            memory: ~

    firewalls:
        public:
            pattern:  ^/(default|users|authorizeGet)$
            security: false
            anonymous: ~

        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        secured_area:
            pattern: ^/
            methods: [GET, POST, PUT, DELETE, TRACE, HEAD, CONNECT]
            stateless: true
            simple_preauth:
                authenticator: apikey_authenticator
            provider: api_key_user_provider